/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mg.rinelfi.manga_scan_downloader.gui;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import mg.rinelfi.manga_scan_downloader.request.TelechargementFichier;

/**
 *
 * @author elier
 */
public class MainWindow extends javax.swing.JFrame {

    private String last_location;
    private Map<String, Object> configuration;
    private List<TelechargementFichier> taches;
    private volatile List<Runnable> threads;
    private final String[] extensions;
    private int nombre_de_file;

    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        initComponents();
        initialiser_boutons();
        this.last_location = System.getProperty("user.home");
        this.configuration = new HashMap<>();
        this.taches = new ArrayList<>();
        this.threads = new ArrayList<>();
        this.extensions = new String[]{"jpg", "png"};
        this.nombre_de_file = 2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root_panel = new javax.swing.JPanel();
        container1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        om_du_projet_pan = new javax.swing.JPanel();
        nom_du_projet_lab = new javax.swing.JLabel();
        nom_du_projet_input = new javax.swing.JTextField();
        container2 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        project_name_panel1 = new javax.swing.JPanel();
        project_name_lab1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chapitre_spin = new javax.swing.JSpinner();
        container3 = new javax.swing.JPanel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        project_name_panel2 = new javax.swing.JPanel();
        project_name_lab2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        premier_page_spin = new javax.swing.JSpinner();
        container4 = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        project_name_panel3 = new javax.swing.JPanel();
        project_name_lab3 = new javax.swing.JLabel();
        sauvegarde_input = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        container5 = new javax.swing.JPanel();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        project_name_panel4 = new javax.swing.JPanel();
        project_name_lab4 = new javax.swing.JLabel();
        lien_input = new javax.swing.JTextField();
        container7 = new javax.swing.JPanel();
        filler21 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        taille_chapitre_fixe_check = new javax.swing.JCheckBox();
        filler23 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        taille_chapitre_fixe_spin = new javax.swing.JSpinner();
        filler24 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        taille_page_fixe_check = new javax.swing.JCheckBox();
        filler25 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        taille_page_fixe_spin = new javax.swing.JSpinner();
        container6 = new javax.swing.JPanel();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        nouveau_btn = new javax.swing.JButton();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        charger_btn = new javax.swing.JButton();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        demarrer_btn = new javax.swing.JButton();
        filler19 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        arreter_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        liste_de_tache_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manga scan downloader");
        setMinimumSize(new java.awt.Dimension(500, 600));
        setResizable(false);

        root_panel.setBackground(new java.awt.Color(255, 255, 255));
        root_panel.setLayout(new javax.swing.BoxLayout(root_panel, javax.swing.BoxLayout.Y_AXIS));

        container1.setBackground(new java.awt.Color(255, 255, 255));
        container1.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        container1.setMinimumSize(new java.awt.Dimension(100, 30));
        container1.setPreferredSize(new java.awt.Dimension(400, 30));
        container1.setLayout(new java.awt.BorderLayout());
        container1.add(filler1, java.awt.BorderLayout.NORTH);
        container1.add(filler2, java.awt.BorderLayout.LINE_END);
        container1.add(filler3, java.awt.BorderLayout.WEST);

        om_du_projet_pan.setBackground(new java.awt.Color(255, 255, 255));
        om_du_projet_pan.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        om_du_projet_pan.setMinimumSize(new java.awt.Dimension(100, 20));
        om_du_projet_pan.setPreferredSize(new java.awt.Dimension(580, 20));
        om_du_projet_pan.setLayout(new java.awt.BorderLayout(5, 0));

        nom_du_projet_lab.setBackground(new java.awt.Color(255, 255, 255));
        nom_du_projet_lab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nom_du_projet_lab.setText("Nom du projet");
        nom_du_projet_lab.setMaximumSize(new java.awt.Dimension(110, 14));
        nom_du_projet_lab.setMinimumSize(new java.awt.Dimension(110, 14));
        nom_du_projet_lab.setPreferredSize(new java.awt.Dimension(110, 14));
        om_du_projet_pan.add(nom_du_projet_lab, java.awt.BorderLayout.LINE_START);
        om_du_projet_pan.add(nom_du_projet_input, java.awt.BorderLayout.CENTER);

        container1.add(om_du_projet_pan, java.awt.BorderLayout.CENTER);

        root_panel.add(container1);

        container2.setBackground(new java.awt.Color(255, 255, 255));
        container2.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        container2.setMinimumSize(new java.awt.Dimension(100, 30));
        container2.setPreferredSize(new java.awt.Dimension(400, 30));
        container2.setLayout(new java.awt.BorderLayout());
        container2.add(filler4, java.awt.BorderLayout.NORTH);
        container2.add(filler5, java.awt.BorderLayout.LINE_END);
        container2.add(filler6, java.awt.BorderLayout.WEST);

        project_name_panel1.setBackground(new java.awt.Color(255, 255, 255));
        project_name_panel1.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        project_name_panel1.setMinimumSize(new java.awt.Dimension(100, 20));
        project_name_panel1.setPreferredSize(new java.awt.Dimension(580, 20));
        project_name_panel1.setLayout(new java.awt.BorderLayout(5, 0));

        project_name_lab1.setBackground(new java.awt.Color(255, 255, 255));
        project_name_lab1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        project_name_lab1.setText("Chapitre");
        project_name_lab1.setMaximumSize(new java.awt.Dimension(110, 14));
        project_name_lab1.setMinimumSize(new java.awt.Dimension(110, 14));
        project_name_lab1.setPreferredSize(new java.awt.Dimension(110, 14));
        project_name_panel1.add(project_name_lab1, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        chapitre_spin.setAlignmentX(0.0F);
        chapitre_spin.setAlignmentY(0.0F);
        chapitre_spin.setMaximumSize(new java.awt.Dimension(70, 30));
        chapitre_spin.setMinimumSize(new java.awt.Dimension(70, 30));
        chapitre_spin.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel1.add(chapitre_spin);

        project_name_panel1.add(jPanel1, java.awt.BorderLayout.CENTER);

        container2.add(project_name_panel1, java.awt.BorderLayout.CENTER);

        root_panel.add(container2);

        container3.setBackground(new java.awt.Color(255, 255, 255));
        container3.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        container3.setMinimumSize(new java.awt.Dimension(100, 30));
        container3.setPreferredSize(new java.awt.Dimension(400, 30));
        container3.setLayout(new java.awt.BorderLayout());
        container3.add(filler7, java.awt.BorderLayout.NORTH);
        container3.add(filler8, java.awt.BorderLayout.LINE_END);
        container3.add(filler9, java.awt.BorderLayout.WEST);

        project_name_panel2.setBackground(new java.awt.Color(255, 255, 255));
        project_name_panel2.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        project_name_panel2.setMinimumSize(new java.awt.Dimension(100, 20));
        project_name_panel2.setPreferredSize(new java.awt.Dimension(580, 20));
        project_name_panel2.setLayout(new java.awt.BorderLayout(5, 0));

        project_name_lab2.setBackground(new java.awt.Color(255, 255, 255));
        project_name_lab2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        project_name_lab2.setText("Page");
        project_name_lab2.setMaximumSize(new java.awt.Dimension(110, 14));
        project_name_lab2.setMinimumSize(new java.awt.Dimension(110, 14));
        project_name_lab2.setPreferredSize(new java.awt.Dimension(110, 14));
        project_name_panel2.add(project_name_lab2, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        premier_page_spin.setAlignmentX(0.0F);
        premier_page_spin.setAlignmentY(0.0F);
        premier_page_spin.setMaximumSize(new java.awt.Dimension(70, 30));
        premier_page_spin.setMinimumSize(new java.awt.Dimension(70, 30));
        premier_page_spin.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel2.add(premier_page_spin);

        project_name_panel2.add(jPanel2, java.awt.BorderLayout.CENTER);

        container3.add(project_name_panel2, java.awt.BorderLayout.CENTER);

        root_panel.add(container3);

        container4.setBackground(new java.awt.Color(255, 255, 255));
        container4.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        container4.setMinimumSize(new java.awt.Dimension(100, 30));
        container4.setPreferredSize(new java.awt.Dimension(400, 30));
        container4.setLayout(new java.awt.BorderLayout());
        container4.add(filler10, java.awt.BorderLayout.NORTH);
        container4.add(filler11, java.awt.BorderLayout.LINE_END);
        container4.add(filler12, java.awt.BorderLayout.WEST);

        project_name_panel3.setBackground(new java.awt.Color(255, 255, 255));
        project_name_panel3.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        project_name_panel3.setMinimumSize(new java.awt.Dimension(100, 20));
        project_name_panel3.setPreferredSize(new java.awt.Dimension(580, 20));
        project_name_panel3.setLayout(new java.awt.BorderLayout());

        project_name_lab3.setBackground(new java.awt.Color(255, 255, 255));
        project_name_lab3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        project_name_lab3.setText("Dossier de sauvegarde");
        project_name_panel3.add(project_name_lab3, java.awt.BorderLayout.LINE_START);
        project_name_panel3.add(sauvegarde_input, java.awt.BorderLayout.CENTER);

        jButton1.setText("Parcourir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        project_name_panel3.add(jButton1, java.awt.BorderLayout.LINE_END);

        container4.add(project_name_panel3, java.awt.BorderLayout.CENTER);

        root_panel.add(container4);

        container5.setBackground(new java.awt.Color(255, 255, 255));
        container5.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        container5.setMinimumSize(new java.awt.Dimension(100, 30));
        container5.setPreferredSize(new java.awt.Dimension(400, 30));
        container5.setLayout(new java.awt.BorderLayout());
        container5.add(filler13, java.awt.BorderLayout.NORTH);
        container5.add(filler14, java.awt.BorderLayout.LINE_END);
        container5.add(filler15, java.awt.BorderLayout.WEST);

        project_name_panel4.setBackground(new java.awt.Color(255, 255, 255));
        project_name_panel4.setMaximumSize(new java.awt.Dimension(2147483647, 20));
        project_name_panel4.setMinimumSize(new java.awt.Dimension(100, 20));
        project_name_panel4.setPreferredSize(new java.awt.Dimension(580, 20));
        project_name_panel4.setLayout(new java.awt.BorderLayout(5, 0));

        project_name_lab4.setBackground(new java.awt.Color(255, 255, 255));
        project_name_lab4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        project_name_lab4.setText("Lien");
        project_name_lab4.setMaximumSize(new java.awt.Dimension(110, 14));
        project_name_lab4.setMinimumSize(new java.awt.Dimension(110, 14));
        project_name_lab4.setPreferredSize(new java.awt.Dimension(110, 14));
        project_name_panel4.add(project_name_lab4, java.awt.BorderLayout.LINE_START);

        lien_input.setToolTipText("http://domaine.com/chemin/vers/le/chapitre/{{chapitre}}/{{page}}.{{ext}}");
        project_name_panel4.add(lien_input, java.awt.BorderLayout.CENTER);

        container5.add(project_name_panel4, java.awt.BorderLayout.CENTER);

        root_panel.add(container5);

        container7.setBackground(new java.awt.Color(255, 255, 255));
        container7.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        container7.setMinimumSize(new java.awt.Dimension(100, 30));
        container7.setPreferredSize(new java.awt.Dimension(400, 30));
        container7.setLayout(new javax.swing.BoxLayout(container7, javax.swing.BoxLayout.LINE_AXIS));
        container7.add(filler21);

        taille_chapitre_fixe_check.setText("taille de chapitre fixe");
        container7.add(taille_chapitre_fixe_check);
        container7.add(filler23);

        taille_chapitre_fixe_spin.setAlignmentX(0.0F);
        taille_chapitre_fixe_spin.setMaximumSize(new java.awt.Dimension(70, 25));
        taille_chapitre_fixe_spin.setMinimumSize(new java.awt.Dimension(70, 25));
        taille_chapitre_fixe_spin.setPreferredSize(new java.awt.Dimension(70, 25));
        container7.add(taille_chapitre_fixe_spin);
        container7.add(filler24);

        taille_page_fixe_check.setText("taille de la page fixe");
        container7.add(taille_page_fixe_check);
        container7.add(filler25);

        taille_page_fixe_spin.setAlignmentX(0.0F);
        taille_page_fixe_spin.setMaximumSize(new java.awt.Dimension(70, 25));
        taille_page_fixe_spin.setMinimumSize(new java.awt.Dimension(70, 25));
        taille_page_fixe_spin.setPreferredSize(new java.awt.Dimension(70, 25));
        container7.add(taille_page_fixe_spin);

        root_panel.add(container7);

        container6.setBackground(new java.awt.Color(255, 255, 255));
        container6.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        container6.setMinimumSize(new java.awt.Dimension(100, 30));
        container6.setPreferredSize(new java.awt.Dimension(400, 30));
        container6.setLayout(new javax.swing.BoxLayout(container6, javax.swing.BoxLayout.LINE_AXIS));
        container6.add(filler16);

        nouveau_btn.setText("Nouveau");
        nouveau_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouveau_btnActionPerformed(evt);
            }
        });
        container6.add(nouveau_btn);
        container6.add(filler17);

        charger_btn.setText("Charger");
        charger_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charger_btnActionPerformed(evt);
            }
        });
        container6.add(charger_btn);
        container6.add(filler18);

        demarrer_btn.setText("Démarrer");
        demarrer_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demarrer_btnActionPerformed(evt);
            }
        });
        container6.add(demarrer_btn);
        container6.add(filler19);

        arreter_btn.setText("Arrêter");
        arreter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arreter_btnActionPerformed(evt);
            }
        });
        container6.add(arreter_btn);

        root_panel.add(container6);

        liste_de_tache_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro de page", "Nom du fichier", "Chargement"
            }
        ));
        jScrollPane1.setViewportView(liste_de_tache_table);

        root_panel.add(jScrollPane1);

        getContentPane().add(root_panel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File(last_location));
        chooser.setDialogTitle("Dossier de déstination");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int selection = chooser.showDialog(root_panel, "Ouvrir");
        if (selection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = chooser.getSelectedFile();
            last_location = selectedFile.isDirectory() ? selectedFile.getPath() : selectedFile.getParent();
            sauvegarde_input.setText(selectedFile.getAbsolutePath());
            this.configuration.put("save location", selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void charger_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charger_btnActionPerformed
        if (information_complet()) {
            bouton_charger();
            final String nom_du_projet = nom_du_projet_input.getText(),
                    dossier_de_sauvegarde = sauvegarde_input.getText(),
                    lien_chapitre = lien_input.getText();
            final int chapitre = Integer.valueOf(chapitre_spin.getValue().toString()),
                    premier_page = Integer.valueOf(premier_page_spin.getValue().toString()),
                    chiffre_chapitre = Integer.valueOf(taille_chapitre_fixe_spin.getValue().toString()),
                    chiffre_page = Integer.valueOf(taille_page_fixe_spin.getValue().toString());
            final boolean chapitre_fixe = taille_chapitre_fixe_check.isSelected(),
                    page_fixe = taille_page_fixe_check.isSelected();
            new Thread(() -> {
                int page_parcours = premier_page;
                boolean prochaine_page_disponible = false;
                DefaultTableModel model_de_table = (DefaultTableModel) liste_de_tache_table.getModel();
                while (model_de_table.getRowCount() > 0) {
                    model_de_table.removeRow(0);
                }
                do {
                    final int page = page_parcours;
                    prochaine_page_disponible = false;
                    TelechargementFichier telechargement = new TelechargementFichier(lien_chapitre, dossier_de_sauvegarde + File.separatorChar + nom_du_projet, chiffre_chapitre, chiffre_page, chapitre, page, chapitre_fixe, page_fixe, extensions);
                    if (telechargement.fichier_existe()) {
                        this.taches.add(telechargement);
                        SwingUtilities.invokeLater(() -> {
                            model_de_table.addRow(new Object[]{page, telechargement.nom_du_fichier(), "En attente"});
                        });
                    }
                    prochaine_page_disponible = telechargement.prochaine_page_disponible();
                    page_parcours++;
                } while (prochaine_page_disponible);
                SwingUtilities.invokeLater(() -> {
                    demarrer_btn.setEnabled(true);
                });
            }).start();
        } else {
            JOptionPane.showMessageDialog(root_panel, "Veuillez verifier les éléments suivants : \n", "Erreur de chargement", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_charger_btnActionPerformed

    private void demarrer_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demarrer_btnActionPerformed
        DefaultTableModel model_table = (DefaultTableModel) liste_de_tache_table.getModel();
        final int TAILLE_TACHE = taches.size();
        bouton_demarrer();
        for (int element = 0; element < TAILLE_TACHE; element++) {
            final int ligne = element;
            Runnable runnable = () -> {
                try {
                    taches.get(ligne).ajouter_observateur_etat(avancement -> {
                        model_table.setValueAt("Téléchargement", ligne, 2);
                        if (((int) avancement) > 0 && ((int) avancement) < 100) {
                            model_table.setValueAt(avancement, ligne, 2);
                        } else {
                            model_table.setValueAt("Terminé", ligne, 2);
                            taches.get(ligne).telechargement_effectue(true);
                            verifier_telechargements();
                        }
                    });
                    taches.get(ligne).telecharger();
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            };
            threads.add(runnable);
        }
        final int TAILLE_THREAD = threads.size();
        for(int i = 0; i < TAILLE_THREAD && i < this.nombre_de_file; i++) {
            new Thread(threads.get(i)).start();
        }
    }//GEN-LAST:event_demarrer_btnActionPerformed

    private void arreter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arreter_btnActionPerformed
        bouton_arreter();
    }//GEN-LAST:event_arreter_btnActionPerformed

    private void nouveau_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveau_btnActionPerformed
        initialiser_boutons();
    }//GEN-LAST:event_nouveau_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arreter_btn;
    private javax.swing.JSpinner chapitre_spin;
    private javax.swing.JButton charger_btn;
    private javax.swing.JPanel container1;
    private javax.swing.JPanel container2;
    private javax.swing.JPanel container3;
    private javax.swing.JPanel container4;
    private javax.swing.JPanel container5;
    private javax.swing.JPanel container6;
    private javax.swing.JPanel container7;
    private javax.swing.JButton demarrer_btn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler19;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler21;
    private javax.swing.Box.Filler filler23;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lien_input;
    private javax.swing.JTable liste_de_tache_table;
    private javax.swing.JTextField nom_du_projet_input;
    private javax.swing.JLabel nom_du_projet_lab;
    private javax.swing.JButton nouveau_btn;
    private javax.swing.JPanel om_du_projet_pan;
    private javax.swing.JSpinner premier_page_spin;
    private javax.swing.JLabel project_name_lab1;
    private javax.swing.JLabel project_name_lab2;
    private javax.swing.JLabel project_name_lab3;
    private javax.swing.JLabel project_name_lab4;
    private javax.swing.JPanel project_name_panel1;
    private javax.swing.JPanel project_name_panel2;
    private javax.swing.JPanel project_name_panel3;
    private javax.swing.JPanel project_name_panel4;
    private javax.swing.JPanel root_panel;
    private javax.swing.JTextField sauvegarde_input;
    private javax.swing.JCheckBox taille_chapitre_fixe_check;
    private javax.swing.JSpinner taille_chapitre_fixe_spin;
    private javax.swing.JCheckBox taille_page_fixe_check;
    private javax.swing.JSpinner taille_page_fixe_spin;
    // End of variables declaration//GEN-END:variables

    private boolean information_complet() {
        final boolean nom_de_projet_valide = !this.nom_du_projet_input.getText().equals(""),
                chapitre_valide = !chapitre_spin.getValue().toString().equals("") || is_number(chapitre_spin.getValue().toString()),
                page_valide = !premier_page_spin.getValue().toString().equals("") || is_number(premier_page_spin.getValue().toString()),
                sauvegarde_valide = !this.sauvegarde_input.getText().equals("");
        return nom_de_projet_valide && chapitre_valide && page_valide && sauvegarde_valide;
    }

    private boolean is_number(String object) {
        return object.matches("^[0-9]*|([0-9]*.[0-9]{1,})$");
    }

    private void verifier_telechargements() {
        int taille_thread = threads.size();
        for(int i = 0, active = 0; i < taille_thread && active < this.nombre_de_file; i++) {
            if(taches.get(i).telechargement_est_effectue()) active++;
            
        }
        
        boolean tache_restant = false;
        for (TelechargementFichier tache : this.taches) {
            if (!tache.fichier_est_telecgarde()) {
                tache_restant = true;
            }
        };
        if (!tache_restant) {
            this.taches.clear();
            this.threads.clear();
            initialiser_boutons();
        }
    }

    private void initialiser_boutons() {
        nouveau_btn.setEnabled(true);
        charger_btn.setEnabled(true);
        demarrer_btn.setEnabled(false);
        arreter_btn.setEnabled(false);
    }

    private void bouton_charger() {
        nouveau_btn.setEnabled(false);
        charger_btn.setEnabled(false);
        demarrer_btn.setEnabled(false);
        arreter_btn.setEnabled(true);
    }

    private void bouton_demarrer() {
        nouveau_btn.setEnabled(false);
        charger_btn.setEnabled(false);
        demarrer_btn.setEnabled(false);
        arreter_btn.setEnabled(true);
    }

    private void bouton_arreter() {
        nouveau_btn.setEnabled(true);
        charger_btn.setEnabled(true);
        demarrer_btn.setEnabled(false);
        arreter_btn.setEnabled(false);
    }
}
